### ISSUE TITLE
There seems to be a bug when creating a new topic.

### ISSUE THREAD

**Issue by erdengk** [casbin/casibase#398] opened 2022-01-03 07:48 UTC
There seems to be a bug. When creating a new topic, clicking multiple times will create multiple identical topics.
Normally, only one should be created.

![image](https://user-images.githubusercontent.com/37730787/147908765-cc2d3510-2917-4d1b-82e2-bed1f5fe1292.png)

**Comment by MayankMittal1** [comment] 2022-02-12 21:08
@erdengk I could not reproduce this issue, could you please help

**Comment by erdengk** [comment] 2022-02-15 12:12
@MayankMittal1  This is a network bug. For example, the server of this website is in A, and the visitor is in city B, which is far away from A. Due to network congestion and other reasons, the response of the website will become very slow, and the user has repeatedly clicked the button to create a new post.
And casnode doesn't seem to prohibit inserting multiple pieces of the same data at the same time. The above problem arises.

You can fix this bug by checking if the casnode does not prohibit the simultaneous insertion of the same data.

**Comment by MayankMittal1** [comment] 2022-02-15 21:12
@erdengk or one more solution is we can have the submit button disabled once it is clicked, this would tell user that request is being processed and will eliminate multiple requests from being generated

**Comment by erdengk** [comment] 2022-02-16 09:50
@MayankMittal1  
This approach is possible, but I think generating multiple identical data should be prohibited programmatically. Because people can access this interface multiple times through scripting, buttons are useless for this situation.

We can add a method that prohibits clicking the button through the front end, and a method that prohibits the generation of the same data in the back end.
What do you think of this method?

**Comment by MayankMittal1** [comment] 2022-02-16 10:27
@erdengk yes this completely makes sense, but will we have to query the database and iterate through the records everytime the user submits a request now assuming that the user is running a script this will create a whole lot of load on the server 
To overcome this what we can do is everytime the user clicks on the create a topic page, a random token (also stored in a database) is generated and supplied to the frontend in a hidden field, which is used to validate the request in the backend(checking if the token exists in the database) if yes then request is validated and the token is deleted from the database (so that it will not be used again) if the token is not present the request is simply rejected

**Comment by erdengk** [comment] 2022-02-17 02:00
@MayankMittal1  

>Every time the user hits the create the topic page, the backend generates a random token (also stored in the database) and provides it to the frontend in a hidden field.

Did you mean this?

Generally speaking, we create a post by sending the text input from the front end to the back end and then persisting it to the database.
So we can't create a token on the front to store in the database and then provide it to the frontend as validation.

Before submitting the data, our data has not yet reached the backend to generate a token that is stored in the database.

**Comment by MayankMittal1** [comment] 2022-02-17 10:19
@erdengk no i meant that the user will make a get request to say /createTopic then the backend will handle this request and render the page
In the same function we will generate the random token and store it in database and supply it in the rendered page

**Comment by erdengk** [comment] 2022-02-17 12:43
@MayankMittal1
Oh, I see what you mean.
It might be possible to do so.
But when multiple people create a new topic at the same time, the front-end needs to send multiple get requests to the back-end, and the back-end also needs to generate multiple tokens, which are then returned to the front-end, and then accept the content text of the topic and persist it to the database. Then prompt the user that the creation was successful.

During this period, the front-end and back-end need to interact twice or more (failure retransmission).

Is there a way to reduce this number of interactions? (Assuming that the network will not be blocked, the problem of failed retransmission will not be considered for the time being)

**Comment by MayankMittal1** [comment] 2022-02-17 19:02
@erdengk Upon further research I have come to following conclusions:
1. The token method is not fully foolproof, any api endpoint we create to generate a random token could also be used in a script and then used to post multiple requests.
2. If we adopt the database query method before accepting, then first it will have a lot of load on the server if requests are made from a script, moreover if the user changes even 1 word in the topic then we can't compare it with previous request data as they will not be equal(but we can use functions which will give a similarity score between two entries and if say it is greater than 0.7 the request is rejected, but this will consume a lot of processing power, and is not very efficient moreover it will not prevent from absolutely random string which a user may post to spam)
3. To make it better we have to club any one of the above two methods with a rate limiter, which will check if concurrent requests are made from the same IP, then reject them

**Comment by MayankMittal1** [comment] 2022-02-23 11:44
@erdengk haven't heard from you for a while, please guide me which approach to take

**Comment by MayankMittal1** [comment] 2022-02-25 14:36
@hsluoyz

**Comment by hsluoyz** [comment] 2022-02-25 14:42
Why makes it so complicated. Just check the duplicated topic title in server-side, add title to DB's index, so the query will be very fast.

For frontend, we can add some UI effect after clicking, like turning to `Publishing...` and makes gray.

**Comment by hsluoyz** [comment] 2022-03-05 13:02
Fixed in: https://github.com/casbin/casnode/pull/420

**Comment by hsluoyz** [comment] 2022-03-05 13:08
@MayankMittal1 your PR doesn't work. I can still do this: https://forum.casbin.com/go/qna

When I click the buttons multiple times, I see the error like "duplicated topics", but I still successfully created so many dup topics.

@Nekotoxin 

![image](https://user-images.githubusercontent.com/3787410/156884358-ef3967f2-f65a-482d-8207-2780e9c97921.png)

**Closed as completed** 2022-03-05 15:22 UTC
Labels: bug, released
